apiVersion: v1
kind: Secret
metadata:
  name: sdlc-secrets
  namespace: sdlc-agent
  labels:
    app.kubernetes.io/name: autonomous-sdlc-agent
    app.kubernetes.io/component: secrets
type: Opaque
stringData:
  # AI Provider API Keys (Base64 encoded in production)
  GEMINI_API_KEY: "your-gemini-api-key-here"
  ANTHROPIC_API_KEY: "your-claude-api-key-here"
  OPENAI_API_KEY: "your-openai-api-key-here"
  BLACKBOX_API_KEY: "your-blackbox-api-key-here"
  
  # Database credentials
  DATABASE_PASSWORD: "secure-database-password"
  
  # Redis password
  REDIS_PASSWORD: "secure-redis-password"
  
  # Session secrets
  SECRET_KEY: "your-flask-secret-key-here"
  SESSION_SECRET: "your-session-secret-here"
  
  # JWT secrets
  JWT_SECRET: "your-jwt-secret-here"
  
  # GitHub integration (optional)
  GITHUB_CLIENT_ID: "your-github-client-id"
  GITHUB_CLIENT_SECRET: "your-github-client-secret"
  
  # Monitoring and logging
  SENTRY_DSN: "your-sentry-dsn-here"
  
---
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: sdlc-agent
  labels:
    app.kubernetes.io/name: autonomous-sdlc-agent
    app.kubernetes.io/component: registry-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoiYXNzaGF0MTk4MWFyIiwicGFzc3dvcmQiOiJnaXRodWJfcGF0XzExQlRMUldVWTBqQnBQTWZzTldU...(base64 encoded docker config)